#!/usr/bin/env python3
"""Generate doc/sources/VERIFICATION.md — the human-rung review worksheet.

Derived entirely from provenance.ttl and the paper sources: for every
source on the ladder it lists the current rung, where the paper cites
it, the recorded check evidence (latest audit note), the access
material the rung-4 gate would hand over (vendored copy + sha256, or
DOI/URL), and the exact provlog commands to grant or refuse a human
rung. Regenerate after any promotion; do not edit by hand.
"""
import pathlib
import re

from rdflib import Graph, Namespace, RDF, RDFS

ROOT = pathlib.Path(__file__).resolve().parent.parent
AIPROV = Namespace("https://w3id.org/aiprov/ns#")
PROV = Namespace("http://www.w3.org/ns/prov#")
DCT = Namespace("http://purl.org/dc/terms/")

RUNG_ORDER = ["unverified", "needs-research", "reference-resolved",
              "ai-confirmed", "source-vendored", "human-confirmed",
              "human-read"]


def cite_locations(sid: str) -> list[str]:
    locs = []
    for f in sorted((ROOT / "paper" / "sections").glob("*.tex")):
        if re.search(r"\\cite\{[^}]*\b" + re.escape(sid) + r"\b", f.read_text()):
            locs.append(f.stem)
    if re.search(r"\\cite\{[^}]*\b" + re.escape(sid) + r"\b",
                 (ROOT / "paper" / "main.tex").read_text()):
        locs.append("main (acknowledgment)")
    return locs


def main():
    g = Graph()
    g.parse(ROOT / "provenance.ttl", format="turtle")
    rows = []
    for s in g.subjects(RDF.type, AIPROV.Source):
        sid = str(s).rsplit("/", 1)[-1]
        title = str(g.value(s, DCT.title) or g.value(s, RDFS.label) or sid)
        rung = "unverified"
        for st in g.objects(s, AIPROV.verificationState):
            r = str(st).rsplit("/", 1)[-1]
            if RUNG_ORDER.index(r) > RUNG_ORDER.index(rung):
                rung = r
        self_cited = (s, AIPROV.selfCitation, None) in g
        files = [str(v) for v in g.objects(s, AIPROV.filePath)]
        hashes = [str(h) for h in g.objects(s, AIPROV.contentHash)]
        links = [str(d) for d in g.objects(s, AIPROV.doi)] + \
                [str(u) for u in g.objects(s, DCT.source)]
        # latest audit note: labels of activities that used this source
        notes = []
        for act in g.subjects(PROV.used, s):
            lbl = g.value(act, RDFS.label)
            if lbl and ("Promotion" in str(lbl) or "REFUSED" in str(lbl)):
                notes.append(str(lbl))
        note = max(notes, key=len) if notes else ""
        rows.append((sid, title, rung, self_cited, files, hashes, links,
                     note, cite_locations(sid)))

    rows.sort(key=lambda r: (-RUNG_ORDER.index(r[2]), r[0]))
    L = ["# Source verification worksheet",
         "",
         "Generated by `scripts/build_review_list.py` from `provenance.ttl` — "
         "do not edit by hand; regenerate after promotions.",
         "",
         "The human rungs are yours alone: `human-confirmed` means you "
         "spot-checked that the source supports the citing sentence; "
         "`human-read` means you read it in full **and** confirm (it subsumes "
         "rung 5). Refusing is first-class: a refusal is logged, changes no "
         "state, and beats silence.",
         ""]
    for sid, title, rung, selfc, files, hashes, links, note, locs in rows:
        flag = " *(self-citation)*" if selfc else ""
        L.append(f"## `{sid}` — {rung}{flag}")
        L.append("")
        L.append(f"**{title}**")
        L.append("")
        if locs:
            L.append(f"- Cited in: {', '.join(locs)}")
        if files:
            for f_, h in zip(files, hashes or [""] * len(files)):
                L.append(f"- Vendored copy: `{f_}` ({h or 'hash in graph'})")
        for link in links:
            L.append(f"- Access: {link}")
        if note:
            L.append(f"- Recorded check: {note}")
        L.append("")
        L.append("```sh")
        L.append(f"python3 scripts/provlog.py promote --id {sid} "
                 f"--to human-confirmed --agent florian-krebs --note \"...\"")
        L.append(f"python3 scripts/provlog.py promote --id {sid} "
                 f"--to human-confirmed --agent florian-krebs --refuse --note \"...\"")
        L.append("```")
        L.append("")
    out = ROOT / "doc" / "sources" / "VERIFICATION.md"
    out.write_text("\n".join(L) + "\n", encoding="utf-8")
    n_vendored = sum(1 for r in rows if r[4])
    print(f"{out}: {len(rows)} sources ({n_vendored} with vendored copies)")


if __name__ == "__main__":
    main()
