#!/usr/bin/env python3
"""Execute a ladder promotion requested via a GitHub issue.

Click-to-confirm without touching the repository: the preview's
"Confirm on GitHub" button opens a prefilled issue; this script runs in
the issues-triggered workflow, verifies the issue author against the
registered operator mapping (doc/operators.json), executes the
promotion with the mapped human agent id, regenerates the worksheet,
commits, and reports back on the issue. The human-only invariant is
preserved because the judgement and the authenticated click are the
operator's; the workflow only transcribes them.

Environment (set by .github/workflows/aiprov-promote.yml):
  ISSUE_TITLE   "aiprov-promote: <source-id> -> <rung>"
  ISSUE_BODY    fields: Action: grant|refuse / Note: <free text>
  ISSUE_AUTHOR  GitHub login of the issue author
  ISSUE_NUMBER  issue number (for the reply comment)
  GH_TOKEN      token for gh CLI (comment + close); optional in dry runs
"""
import json
import os
import pathlib
import re
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
HUMAN_RUNGS = {"human-confirmed", "human-read"}


def reply_and_close(number: str, body: str, ok: bool) -> None:
    if not os.environ.get("GH_TOKEN"):
        print(f"[dry-run] would comment on #{number}: {body}")
        return
    subprocess.run(["gh", "issue", "comment", number, "--body", body],
                   cwd=ROOT, check=False)
    subprocess.run(["gh", "issue", "close", number,
                    "--reason", "completed" if ok else "not planned"],
                   cwd=ROOT, check=False)


def fail(number: str, msg: str) -> None:
    print(f"REFUSED: {msg}", file=sys.stderr)
    reply_and_close(number, f"**Promotion not executed.** {msg}\n\n---\n"
                            f"_Generated by [Claude Code](https://claude.ai/code)_",
                    ok=False)
    sys.exit(0)  # a refused request is a handled outcome, not a CI failure


def main() -> None:
    title = os.environ.get("ISSUE_TITLE", "")
    body = os.environ.get("ISSUE_BODY", "")
    author = os.environ.get("ISSUE_AUTHOR", "")
    number = os.environ.get("ISSUE_NUMBER", "0")

    m = re.match(r"aiprov-promote:\s*(\S+)\s*->\s*(\S+)\s*$", title)
    if not m:
        fail(number, f"title `{title}` does not match "
                     "`aiprov-promote: <source-id> -> <rung>`.")
    source_id, rung = m.group(1), m.group(2)

    action = (re.search(r"^Action:\s*(\S+)", body, re.M) or [None, ""])[1]
    note_m = re.search(r"^Note:\s*(.+)$", body, re.M | re.S)
    note = note_m.group(1).strip() if note_m else ""
    if action not in ("grant", "refuse"):
        fail(number, "body must contain `Action: grant` or `Action: refuse`.")
    if not note or "required" in note.lower()[:80] and "<" in note:
        fail(number, "body must contain a non-empty `Note:` with your "
                     "reasoning — the note is the recorded judgement.")

    operators = json.loads((ROOT / "doc" / "operators.json").read_text())
    agent = operators.get(author)
    if not agent:
        fail(number, f"GitHub user `{author}` is not a registered operator "
                     "(doc/operators.json). Human rungs stay with registered "
                     "humans.")
    if rung in HUMAN_RUNGS:
        pass  # mapped human agent grants it — the invariant the validator checks
    cmd = ["python3", "scripts/provlog.py", "promote", "--id", source_id,
           "--to", rung, "--agent", agent,
           "--note", f"{note} (granted via GitHub issue #{number} by "
                     f"@{author}; the click and the judgement are the "
                     f"operator's, the workflow transcribed them)"]
    if action == "refuse":
        cmd.append("--refuse")
    r = subprocess.run(cmd, cwd=ROOT, capture_output=True, text=True)
    if r.returncode != 0:
        fail(number, f"tooling refused: ```{(r.stderr or r.stdout).strip()}```")

    subprocess.run(["python3", "scripts/build_review_list.py"], cwd=ROOT,
                   check=False)
    subprocess.run(["git", "add", "provenance.ttl", "doc/sources"], cwd=ROOT,
                   check=True)
    verb = "refusal of" if action == "refuse" else "promotion to"
    subprocess.run(["git", "-c", "user.name=aiprov-promote[bot]",
                    "-c", "user.email=noreply@github.com", "commit", "-m",
                    f"{source_id}: {verb} {rung} via issue #{number} "
                    f"by @{author}"], cwd=ROOT, check=True)
    subprocess.run(["git", "push"], cwd=ROOT, check=True)
    reply_and_close(number,
                    f"**Done.** `{source_id}` {verb} `{rung}` recorded as "
                    f"agent `{agent}`; graph and worksheet committed.\n\n"
                    f"```\n{r.stdout.strip()}\n```\n\n---\n"
                    f"_Generated by [Claude Code](https://claude.ai/code)_",
                    ok=True)


if __name__ == "__main__":
    main()
